name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    # Permissions block is optional, useful for dependabot checks
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew clean test
      - name: Publish Test Report
        if: success() || failure()
        uses: AutoModality/action-xunit-viewer@v1 #phoenix-actions/test-reporting@v12 #mikepenz/action-junit-report@v3 #scacap/action-surefire-report@v1
        with:
          results: '**/build/reports/tests/test'
          #report_paths: '**/build/test-results/test/TEST-*.xml'
          #name: JEST Tests
          #path: '**/build/test-results/test/TEST-*.xml'
          #reporter: java-junit
      - name: Attach the report
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.xunit-viewer.outputs.report-name }}
          path: ${{ steps.xunit-viewer.outputs.report-dir }}